import { useEffect, useState } from "react";
import { useAuth } from "../AuthContext";
import "./UserPreferences.css";

export default function UserPrerenences() {
  const { token } = useAuth();
  const [preferences, setPreferences] = useState<string>("");

  async function fetchPreferences() {
    try {
      const res = await fetch(
        `${import.meta.env.VITE_API_URL}/users/preferences`,
        {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );

      if (!res.ok) {
        console.error("Failed to fetch preferences");
        return;
      }

      const data = await res.json();
      setPreferences(data.preferences);
    } catch (err) {
      console.error(err);
    }
  }

  useEffect(() => {
    fetchPreferences();
  }, []);

  return (
    <div className="user-preferences-wrapper">
      <div className="user-preferences-info">
        <h3>🤖 How It Works</h3>
        <p>
          This taste profile is generated by an AI 🤖 every 5 minutes
          if you update your favourites or ratings.
          Add meals to your favourites and rate them, then refresh to see your unique taste profile!
        </p>
      </div>

      <div className="user-preferences-content">
        <h3>🍽️ Your Taste Profile</h3>
        {preferences ? (
          <p>{preferences}</p>
        ) : (
          <p>
            🤖 No profile yet! Add some favourites or ratings,
            wait ~5 minutes and refresh this page to see what the AI cooks up for you.
          </p>
        )}
      </div>
    </div>
  );
}
